name: test

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install valgrind
        run: sudo apt-get update && sudo apt-get install -y valgrind
      - name: Build
        run: make CXXFLAGS="-g -Wall -Wextra -Weffc++ -Werror -std=c++11 -Iinclude"
      - name: Test
        run: make test
